//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaChamadoTecnico.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    public partial class Atendente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Atendente()
        {
            this.Chamado = new HashSet<Chamado>();
        }
    
        public int IdAtendente { get; set; }

        [DisplayName("Nome")]
        public string NomeAtendente { get; set; }

        [DisplayName("Telefone")]
        public string TelefoneAtenente { get; set; }

        [DisplayName("Email")]
        public string EmailAtendente { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Chamado> Chamado { get; set; }
    }
}
