//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaChamadoTecnico.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    public partial class Chamado
    {
        public int IdChamado { get; set; }
        public Nullable<int> IdCliente { get; set; }

        public Nullable<int> IdAtendente { get; set; }

        [DisplayName("Título")]
        [Required(ErrorMessage = "O Título é obrigatório !")]
        public string TituloChamado { get; set; }

        [DataType(DataType.MultilineText)]
        [DisplayName("Descrição")]
        [Required(ErrorMessage = "A descrição é obrigatória !")]
        public string DescricaoChamado { get; set; }

        [DisplayName("Estado")]
        public string EstadoChamado { get; set; }

        [DataType(DataType.MultilineText)]
        [DisplayName("Observação")]
        public string ObsevacaoChamado { get; set; }

        [DisplayName("Data de Criação")]
        public Nullable<System.DateTime> DataCriacaoChamado { get; set; }

        [DisplayName("Data de Encerramento")]
        public Nullable<System.DateTime> DataEncerramentoChamado { get; set; }

        public virtual Atendente Atendente { get; set; }
        public virtual Cliente Cliente { get; set; }
    }
}
