//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaChamadoTecnico.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    public partial class Cliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cliente()
        {
            this.Chamado = new HashSet<Chamado>();
        }

        public int IdCliente { get; set; }

        [Required(ErrorMessage = "O Nome é obrigatório !")]
        public string NomeCliente { get; set; }
        public string TelefoneCliente { get; set; }
        public string EmailCliente { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Chamado> Chamado { get; set; }

        [DataType(DataType.Password)]
        [DisplayName("Senha")]
        public string SenhaUsuario { get; set; }

        [DataType(DataType.Password)]
        [DisplayName("Confimação")]
        public string ConfirmaUsuario { get; set; }

        [DisplayName("Usuário")]
        public string NomeUsuario { get; set; }
    }
}
