//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaChamadoTecnico.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonUser
    {
        public int IdPersoUser { get; set; }
        public Nullable<int> IdPerson { get; set; }
        public string IdUser { get; set; }
    }
}
